- name: variables to print
  hosts: web
  vars: #play level all tasks in this play have access to it
    COURSE: "DevOps with AWS"
    DURATION: "120HRS"
    TRAINER: "Sivakumar Reddy M"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, duration is {{DURATION}}, trainer is {{TRAINER}}"


  - name: print the information
    vars:
      COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, duration is {{DURATION}}, trainer is {{TRAINER}}"