- name: variable from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: Please enter the course name
    private: false #not confidential
  - name: DURATION
    prompt: please enter the duration
    private: false #not confidential
  - name: TRAINER
    prompt: please enter the trainer name
    private: false #not confidential
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, duration is {{DURATION}}, trainer is {{TRAINER}}"