- name: variables from inventory
  hosts: web
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, duration is {{DURATION}}, trainer is {{TRAINER}}"