- name: check a number is less than 10 or not
  hosts: web
  connection: local
  vars_prompt:
  - name: number
    prompt: Please enter the number
    private: false #not confidential
  tasks:
  -name: print this if less than 10
   ansible.builtin.debus:
     msg: "Given number {{ number }} less than 10"
   when: number < 10 #conditional statement

  -name: print this if greater than or equal to 10
   ansible.builtin.debug:
     msg: "Given number {{ number }} greater than or equal to 10"
   when: number >= 10